# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_treasure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.FileField(default=b'media/default.png', upload_to=b'treasure_images'),
        ),
    ]
