# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20170711_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasure',
            name='likes',
        ),
        migrations.AddField(
            model_name='treasure',
            name='about',
            field=models.CharField(default=b'0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='treasure',
            name='breed',
            field=models.CharField(default=b'0000000', max_length=100),
        ),
        migrations.AddField(
            model_name='treasure',
            name='dog',
            field=models.CharField(default=b'0000000', max_length=100),
        ),
    ]
