# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_treasure_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='about',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
