# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20170712_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='about',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(default=b'', upload_to=b'treasure_images'),
        ),
    ]
