# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20170713_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='age',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
